### ISSUE TITLE
ERROR: sorry, it was not possible to establish a connection to the server.

### ISSUE THREAD

**Issue by Torrio888** [GouveaHeitor/nipe#10]
when i try to start nipe I get this error
ERROR: sorry, it was not possible to establish a connection to the server.

**Comment by GouveaHeitor** [comment]
What is your system?

**Comment by Torrio888** [comment]
Linux Mint 18.2 64-bit

**Comment by Torrio888** [comment]
Output of the sudo perl nipe.pl install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tor is already the newest version (0.3.0.10-1~xenial+1).
iptables is already the newest version (1.6.0-2ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
--2017-08-28 17:03:08--  http://gouveaheitor.github.io/nipe/debian/torrc
Resolving gouveaheitor.github.io (gouveaheitor.github.io)... 151.101.113.147, 2a04:4e42:1b::403
Connecting to gouveaheitor.github.io (gouveaheitor.github.io)|151.101.113.147|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://heitorgouvea.me/nipe/debian/torrc [following]
--2017-08-28 17:03:08--  http://heitorgouvea.me/nipe/debian/torrc
Resolving heitorgouvea.me (heitorgouvea.me)... 192.30.252.153, 192.30.252.154
Connecting to heitorgouvea.me (heitorgouvea.me)|192.30.252.153|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 454 [application/octet-stream]
Saving to: ‘torrc’

torrc               100%[===================>]     454  --.-KB/s    in 0s      

2017-08-28 17:03:09 (28,3 MB/s) - ‘torrc’ saved [454/454]

**Comment by GouveaHeitor** [comment]
Run the commands and show me the response:

$ perl -v
$ iptales -v

**Comment by Torrio888** [comment]
This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi
(with 58 registered patches, see perl -V for more detail)

iptables v1.6.0:

**Comment by dnkls** [comment]
The same error

**Comment by xanthuiop** [comment]
same error

**Comment by GouveaHeitor** [comment]
This error was resolved in commit 5254c3a422d69666e07d008a2025cf8dd152281c

**Comment by PieElecAm** [comment]
Hi,

I'm receiving same error on TurnKey-Linux-Jessie

I've successfuly gotten this tool to run on 3 different machines, just this one doesn't want to work. I've installed also 
"apt-get install perlbrew - && curl -L http://xrl.us/installperlnix | bash"

And it's still not running.

When I run any perl nipe.pl command it gives no output, and when I run: perl nipe.pl status it shows "[!] ERROR: sorry, it was not possible to establish a connection to the server."
